In [15]:
import numpy as np

In [16]:
array = np.arange(1, 101)

In [17]:
array[::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [18]:
array[-1::-2]

array([100,  98,  96,  94,  92,  90,  88,  86,  84,  82,  80,  78,  76,
        74,  72,  70,  68,  66,  64,  62,  60,  58,  56,  54,  52,  50,
        48,  46,  44,  42,  40,  38,  36,  34,  32,  30,  28,  26,  24,
        22,  20,  18,  16,  14,  12,  10,   8,   6,   4,   2])

In [19]:
array[1::3] = 3
array

array([  1,   0,   3,   4,   0,   6,   7,   0,   9,  10,   0,  12,  13,
         0,  15,  16,   0,  18,  19,   0,  21,  22,   0,  24,  25,   0,
        27,  28,   0,  30,  31,   0,  33,  34,   0,  36,  37,   0,  39,
        40,   0,  42,  43,   0,  45,  46,   0,  48,  49,   0,  51,  52,
         0,  54,  55,   0,  57,  58,   0,  60,  61,   0,  63,  64,   0,
        66,  67,   0,  69,  70,   0,  72,  73,   0,  75,  76,   0,  78,
        79,   0,  81,  82,   0,  84,  85,   0,  87,  88,   0,  90,  91,
         0,  93,  94,   0,  96,  97,   0,  99, 100])