In [63]:
import numpy as np
from sklearn.preprocessing import StandardScaler

In [64]:
X_train = np.array([[ 1., -1.,  2.],
                     [ 2.,  0.,  0.],
                     [ 0.,  1., -1.]])
X_test = np.array([[ 2., -1.,  1.],
                     [ 3.,  3.,  -1.],
                     [ 1.,  1., 1.]])

In [65]:
scaler = StandardScaler()
X_train_transform = scaler.fit_transform(X_train)
X_train_transform

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [66]:
np.mean(X_train_transform, axis=0)

array([0., 0., 0.])

In [67]:
np.std(X_train_transform, axis=0)

array([1., 1., 1.])

In [68]:
scaler.transform(X_test)

array([[ 1.22474487, -1.22474487,  0.53452248],
       [ 2.44948974,  3.67423461, -1.06904497],
       [ 0.        ,  1.22474487,  0.53452248]])