In [22]:
import numpy as np
from sklearn.model_selection import train_test_split

In [23]:
X = np.arange(1,21).reshape(10,-1)
y = np.arange(1,11)
X, y

(array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=False, test_size=0.2)
X_train, X_test, y_train, y_test

(array([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]]),
 array([[17, 18],
        [19, 20]]),
 array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 9, 10]))